/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class vn_haipq_bwimage_BWImage */

#ifndef _Included_vn_haipq_bwimage_BWImage
#define _Included_vn_haipq_bwimage_BWImage
#ifdef __cplusplus
extern "C" {
#endif
#undef vn_haipq_bwimage_BWImage_PICK_FROM_CAMERA
#define vn_haipq_bwimage_BWImage_PICK_FROM_CAMERA 1L
#undef vn_haipq_bwimage_BWImage_PICK_FROM_FILE
#define vn_haipq_bwimage_BWImage_PICK_FROM_FILE 2L
/*
 * Class:     vn_haipq_bwimage_BWImage
 * Method:    convertToGrayscale
 * Signature: (Landroid/graphics/Bitmap;Landroid/graphics/Bitmap;)V
 */
JNIEXPORT void JNICALL Java_vn_haipq_bwimage_BWImage_convertToGrayscale
  (JNIEnv *, jobject, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
